
const challenges = [
  {
    name: "Playable Mortal Kombat Characters",
    nameAsRule: "Your password must be a playable Mortal Kombat character",
    failedMessage: "[PASS] is not a playable Mortal Kombat character",
    possible: [
      "johnny cage",
      "kano",
      "liu kang",
      "raiden",
      "scorpion",
      "sonya blade",
      "sub-zero",
      "goro",
      "shang tsung",
      "reptile",
      "baraka",
      "jade",
      "jax",
      "kintaro",
      "kitana",
      "kung lao",
      "mileena",
      "noob saibot",
      "shao khan",
      "smoke",
      "chameleon",
      "cyrax",
      "ermac",
      "kabal",
      "khameleon",
      "motaro",
      "nightwolf",
      "rain",
      "sektor",
      "sheeva",
      "sindel",
      "stryker",
      "meat",
      "bo rai cho",
      "frost"
    ]
  }
];