
const challenges = [
  {
    name: "Playable Mortal Kombat Characters",
    nameAsRule: "Your password must be a playable Mortal Kombat character",
    failedMessage: "[PASS] is not a playable Mortal Kombat character",
    possible: [
      "johnny cage",
      "kano",
      "liu kang",
      "raiden",
      "scorpion",
      "sonya blade",
      "sub-zero",
      "goro",
      "shang tsung",
      "reptile",
      "baraka",
      "jade",
      "jax",
      "kintaro",
      "kitana",
      "kung lao",
      "mileena",
      "noob saibot",
      "shao khan",
      "smoke",
      "chameleon",
      "cyrax",
      "ermac",
      "kabal",
      "khameleon",
      "motaro",
      "nightwolf",
      "rain",
      "sektor",
      "sheeva",
      "sindel",
      "stryker",
      "meat",
      "bo rai cho",
      "frost"
    ]
  },

  {
    name: "First Name of Bob's Burgers characters",
    nameAsRule: "Your password MUST be the first name of a Bob's Burgers character",
    failedMessage: "[PASS] is not a Bob's Burgers character",

    possible: [
      "Mike",
      "Bob",
      "LINDA",
      "GENE",
      "LOUISE",
      "TINA",
      "TEDDY",
      "MORT",
      "RUDY",
      "JIMMY",
      "ANDY",
      "OLLIE",
      "JOCELYN",
      "TAMMY",
      "HELEN",
      "TREV",
      "MARSHMALLOW",
      "BOO BOO",
      "DARRYL",
      "PHILLIP",
      "ALEX",
      "ART",
      "RANDY",
      "KURT",
      "LOGAN",
      "SASHA"
    ]
  }
];